### ISSUE TITLE
Few questions before switching 

### ISSUE THREAD

**Issue by kkharji** [zgpio/brew.nvim#4]
Hey @zgpio , hope you don’t mind this Q/A issue. I’d like to use brew a replacement for my builtin package manager. But I have few questions: 

1. Are you planning to maintain this? can I depend on it long term.
2. Can I have plugins defined across several lua file ? I tend to be against having all my plugins definitions in one file.

Thanks  🙏

**Comment by zgpio** [comment]
Sorry for the late reply, I only saw the message today
1. I intend to make this plugin better, I need to add tests to improve the stability of the plugin，but I have been busy recently.
2. It should be able to configure plugins in different files, which needs to be well designed.

**Comment by kkharji** [comment]
@zgpio no problems.

If you can take a look at my main function that register plugins and configurations and tell me if its feasible to replace without changing anything in the files that uses the function I can start migrating to brew.nvim and perhaps work together on todos. 
https://github.com/tami5/nvim/blob/main/fnl/lib/depm.fnl#L103
Thanks
